backend:
  image:
    registry: docker.io
    repository: 2470/home_task
    tag: latest
    pullPolicy: Always

  resources:
    limits:
      cpu: "500m"
      memory: "1Gi"
    requests:
      cpu: "250m"
      memory: "512Mi"

  env:
    DATABASE_URL: "postgres://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/{{ .Values.postgres.database }}"
    ALLOWED_ORIGINS: "{{ .Values.backend.env.ALLOWED_ORIGINS }}"

  livenessProbe:
    httpGet:
      path: /health
      port: 8000
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

  readinessProbe:
    httpGet:
      path: /readiness
      port: 8000
    initialDelaySeconds: 15
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80

  monitoring:
    enabled: true
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
        namespace: monitoring

postgres:
  host: "my-release-fastapi-app-postgres"
  port: "5432"

  resources:
    limits:
      cpu: "500m"
      memory: "1Gi"
    requests:
      cpu: "250m"
      memory: "512Mi"

  persistence:
    enabled: true
    storageClass: "standard"
    size: "10Gi"

  backup:
    enabled: true
    schedule: "0 3 * * *"
    storage:
      type: s3
      s3Bucket: "postgres-backups"

  service:
    type: ClusterIP
    port: 5432
    targetPort: 5432

  replicaCount: 1

pgadmin:
  email: "oaluyi@yahoo.co.uk"
  image:
    tag: latest
    pullPolicy: Always
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"

  persistence:
    enabled: true
    storageClass: "standard"
    size: "5Gi"

  ingress:
    enabled: true
    hosts:
      - dayonesolver.co.uk  

  tls:
    secretName: pgadmin-tls
    hosts:
      - dayonesolver.co.uk

service:
  backend:
    type: ClusterIP
    port: 8080
    targetPort: 8000

  pgadmin:
    type: ClusterIP
    port: 80
    targetPort: 80
