#base64 encoded strings
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-helm-chart.fullname" . }}-secret
type: Opaque
data:
  ALLOWED_ORIGINS: aHR0cHMvLzpkYXlvbmVzb2x2ZXIuY28udWs=
  DB_HOST: bXktcmVsZWFzZS1mYXN0YXBpLWFwcC1wb3N0Z3Jlcw==
  DB_NAME: b3p6eV9kYg==
  DB_PASS: Z2FsYWN0aWNfQDIzKzE=
  DB_PORT: NTQzMg==
  DB_USER: b3p6eQ==
  PGADMIN_DEFAULT_PASSWORD: ZGFtaUBuMjNfNA==